### ISSUE TITLE
 Cannot find module 'expect/build/jasmineUtils' from 'node_modules/jest-marbles/umd/jest-marbles.js'

### ISSUE THREAD

**Issue by VenkataPakalapati** [just-jeb/jest-marbles#403]
ran into this issue after upgrading to angular 13. Is there a fix in works or any workaround for now?

```
Test suite failed to run

    Cannot find module 'expect/build/jasmineUtils' from 'node_modules/jest-marbles/umd/jest-marbles.js'

    Require stack:
      node_modules/jest-marbles/umd/jest-marbles.js
      src/app/common/standalone-error/effects/standalone-error.effect.spec.ts

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:491:11)
      at webpackUniversalModuleDefinition (node_modules/jest-marbles/umd/jest-marbles.js:3:28)
      at Object.<anonymous> (node_modules/jest-marbles/umd/jest-marbles.js:10:3)
```

**Additional Info**

    "jest": "28.1.1",
    "jest-marbles": "3.0.2",
    "jest-when": "3.4.1",

**Comment by bulldog98** [comment]
This is caused by #401
