### ISSUE TITLE
Can't run README.md examples    TypeError: pipe_1.pipeFromArray(...) is not a function

### ISSUE THREAD

**Issue by KhalfaniW** [just-jeb/jest-marbles#571]
**Description:**

I can't run the examples in the README. I don't know how to run any tests. 

**Example Test (failing):**

```typescript
it('Should concatenate two cold observables into single cold observable', () => {
    const a = cold('-a-|');
    const b = cold('-b-|');
    const expected = '-a--b-|';
    expect(a.pipe(concat(b))).toBeMarble(expected);
});
```

**Error Message:**

```
TypeError: pipe_1.pipeFromArray(...) is not a function

      5 |     const b = cold('-b-|');
      6 |     const expected = '-a--b-|';
    > 7 |     expect(a.pipe(concat(b))).toBeMarble(expected);
        |              ^
      8 | });
      9 |

      at ColdObservable.Object.<anonymous>.Observable.pipe (node_modules/rxjs/src/internal/Observable.ts:437:37)
      at Object.pipe (__tests__/x.js:7:14)
```

**package.json:**

```json
{
  "name": "tmp-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "node --experimental-vm-modules node_modules/jest/bin/jest.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "jest": "^29.5.0",
    "jest-marbles": "^3.1.0"
  },
  "dependencies": {
    "rxjs": "^7.0.1"
  }
}
```

**Comment by KhalfaniW** [comment]
The new syntax is 

```js
   expect(concat(a,b)).toBeMarble(expected);
```
The examples not being updated is confusing to beginners like myself

**Comment by just-jeb** [comment]
The error you are seeing is not caused by jest-marbles — it is a Jest ESM/CJS interop problem with RxJS.

**What's happening:** You set `"type": "module"` in your package.json, which tells Node to treat `.js` files as ESM. However, Jest does not support native ESM by default. When Jest loads RxJS's CJS bundle in an ESM context without the right transform configuration, the internal pipe helpers are not wired up correctly, producing `pipeFromArray(...) is not a function`.

**Fix:** Either remove `"type": "module"` and use the standard CJS setup, or configure Jest for ESM per the [official docs](https://jestjs.io/docs/ecmascript-modules). Your test script already uses `--experimental-vm-modules` (the ESM flag), but you also need:

1. A `jest.config.js` (or `jest.config.mjs`) with `extensionsToTreatAsEsm` and a proper `transform`.
2. Or switch back to CJS: remove `"type": "module"` from your package.json and use the normal `node_modules/jest/bin/jest.js` invocation without `--experimental-vm-modules`.

The jest-marbles import path (`from 'jest-marbles'`) is correct — both CJS and ESM builds are published, and the types are in place. The README examples are valid for a correctly configured Jest environment. Verified working in 3.2.0 against Jest 30 with jest-circus.

Also note: the README examples showing `concat(b)` and `merge(e2)` are missing the RxJS operator imports (e.g. `import { concat } from 'rxjs'`) — those need to be imported separately from RxJS, they are not part of jest-marbles. This is an omission in the README examples, not a bug.

Closing as a consumer configuration issue. If there is a specific API breakage (not an ESM setup problem), please open a new issue with a minimal reproduction using CJS.
